<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" Version="1.6.0" />
    <PackageReference Include="FluentValidation" Version="12.1.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="12.1.1" />
    <PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="3.1.2" />
    <PackageReference Include="Microsoft.AspNetCore.JsonPatch.SystemTextJson" Version="10.0.9" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.9.0" />
    <PackageReference Include="OpenTelemetry.Api" Version="1.18.0" />
    <PackageReference Include="SFA.DAS.Configuration.AzureTableStorage" Version="17.1.165" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="10.0.3" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="10.0.0" />
    <PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" Version="7.0.3" />
    <PackageReference Include="SFA.DAS.Api.Common" Version="17.1.196" />
    <PackageReference Include="SFA.DAS.Encoding" Version="1.1.76" />
    <PackageReference Include="SFA.DAS.InputValidation" Version="17.1.100" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.0">
      <GeneratePathProperty>true</GeneratePathProperty>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="9.0.4" />
  </ItemGroup>
     <ItemGroup>
    <Content Update="appsettings.Development.json">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
    <Content Update="appsettings.json">
      <CopyToPublishDirectory>Never</CopyToPublishDirectory>
    </Content>
  </ItemGroup>
  <PropertyGroup>
    <OpenApiGenerateDocumentsOnBuild>true</OpenApiGenerateDocumentsOnBuild>
    <OpenApiDocumentsDirectory>$(MSBuildThisFileDirectory)</OpenApiDocumentsDirectory>
    <AssemblyName>SFA.DAS.FundingProjection.Api</AssemblyName>
    <RootNamespace>SFA.DAS.FundingProjection.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FundingProjection.Data\FundingProjection.Data.csproj" />
    <ProjectReference Include="..\FundingProjection.Domain\FundingProjection.Domain.csproj" />
  </ItemGroup>
</Project>